name: "Mark or close stale issues and PRs"
 
on:
  schedule:
  - cron: "30 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v6.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 25
        days-before-close: 5"
        stale-pr-label: "stale"
        stale-issue-label: "stale"
        exempt-issue-labels: "bug,enhancement,pinned,security"
        exempt-pr-labels: "bug,enhancement,pinned,security"
